# Numpy Crash Course

In [1]:
import numpy as np

In [2]:
np.__version__

'1.26.3'

## Creating Arrays

In [3]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [4]:
type(my_list)

list

In [5]:
arr = np.array(my_list) 

In [6]:
arr

array([0, 1, 2, 3, 4, 5])

In [7]:
type(arr)

numpy.ndarray

In [8]:
type(my_list)

list

In [9]:
np.arange(5) 

array([0, 1, 2, 3, 4])

In [10]:
np.arange(3.0) 

array([0., 1., 2.])

In [11]:
np.arange(10) 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [13]:
np.arange(10,20) 

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [14]:
np.arange(20,10) 

array([], dtype=int32)

In [15]:
np.arange(-20,10) 

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [16]:
np.arange(-16,10) 

array([-16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,
        -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [17]:
np.arange(-20,-10) 

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [18]:
np.arange(30,20)  # 1st arg always be < then 2nd arg

array([], dtype=int32)

In [19]:
b = np.arange(-30,20)
b

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [20]:
np.arange(10,10) 

array([], dtype=int32)

In [21]:
np.arange(-20,20) 

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9,  10,  11,  12,  13,  14,  15,  16,  17,  18,
        19])

In [22]:
np.arange(10,30,5)  # 10- starting from 30- end point 5 - step count

array([10, 15, 20, 25])

In [23]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [24]:
np.arange(10,30,5,1)

TypeError: Cannot interpret '1' as a data type

In [28]:
b1 = np.zeros(2) #parameter tunning
b1

array([0., 0.])

In [29]:
np.zeros(5,dtype=int) #hyperparameter tunning 

array([0, 0, 0, 0, 0])

In [30]:
zero = np.zeros((2,2))
zero

array([[0., 0.],
       [0., 0.]])

In [33]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [34]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [35]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [36]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [37]:
np.zeros((10,30))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0

In [ ]:
np.zeros((5,10)) # bydefaul 1arge -- will give row & 2nd arg - columns

In [38]:
n = (5,7)
n1 = (6,8)
print(np.zeros(n)) # parameter tunnin g
#print(np.zeros(n1,dtype=int)) ## hypyerparameter tunning 

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [39]:
print(np.zeros(n1))

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [41]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [42]:
np.ones(4)

array([1., 1., 1., 1.])

In [43]:
n

(5, 7)

In [44]:
np.ones(n)

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [45]:
np.ones((5,4),dtype=int) # by default 5- rows & 4 - columns

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [46]:
np.twos((2,3))

AttributeError: module 'numpy' has no attribute 'twos'

In [47]:
np.ones((2,4)) 

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [48]:
np.ones((6,10),dtype = int) 

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [49]:
np.twos((2,4))

AttributeError: module 'numpy' has no attribute 'twos'

In [50]:
np.three((2,4))

AttributeError: module 'numpy' has no attribute 'three'

## please add new notebook & compare with np & *

In [ ]:
>>> from numpy import *  
>>> arange(3)

In [ ]:
range(12)
list(range(12))

In [ ]:
y = list(range(12))
y

In [3]:
np.

SyntaxError: invalid syntax (2469254449.py, line 1)

In [ ]:
>>> from numpy import *
>>> zeros(5)

In [51]:
np.threes((3,2)) 

AttributeError: module 'numpy' has no attribute 'threes'

In [52]:
rand(3,2)
random.rand(3,2)

NameError: name 'rand' is not defined

In [65]:
np.random.rand(4)

array([0.11370788, 0.88550077, 0.7456773 , 0.6879657 ])

In [66]:
np.rand(4)

AttributeError: module 'numpy' has no attribute 'rand'

In [64]:
np.random.rand(2,4)

array([[0.76507331, 0.9297429 , 0.24693827, 0.59895637],
       [0.39939959, 0.87591168, 0.27643314, 0.80868776]])

In [69]:
np.random.randint(2,20) # 2nd argument is exlusive 

17

In [76]:
np.random.randint(0,2)

0

In [84]:
np.random.randint(1,10,4)

array([8, 9, 7, 4])

In [ ]:
np.random.randint(1,3,5)

In [85]:
np.random.randint(30,20,10) 

ValueError: low >= high

In [88]:
np.random.randint(1)  

0

In [89]:
np.random.randint(5,9)  #GET THE VALUE <=1 & >=5

6

In [ ]:
np.random.randint(10,21,3)

In [ ]:
np.random.randint(1,12,10)

In [90]:
np.random.randint(10,40,(10,10)) #generre the element 10 -30 with 4*4 mtri

array([[36, 21, 29, 39, 33, 11, 32, 13, 12, 24],
       [32, 21, 38, 25, 12, 12, 22, 29, 21, 10],
       [24, 19, 38, 32, 24, 11, 24, 34, 11, 21],
       [38, 25, 23, 25, 12, 11, 33, 36, 39, 22],
       [34, 10, 28, 21, 13, 17, 20, 34, 39, 37],
       [20, 33, 25, 11, 27, 38, 24, 29, 35, 12],
       [39, 21, 36, 30, 37, 35, 15, 30, 17, 11],
       [31, 15, 26, 19, 27, 13, 37, 18, 33, 23],
       [23, 37, 24, 19, 10, 30, 16, 19, 25, 17],
       [17, 11, 21, 15, 10, 11, 33, 20, 12, 31]])

In [91]:
b = np.random.randint(10,20,(5,4))
b

array([[15, 12, 11, 17],
       [13, 18, 19, 13],
       [11, 12, 17, 12],
       [10, 17, 18, 15],
       [13, 12, 19, 19]])

In [92]:
b[:]

array([[15, 12, 11, 17],
       [13, 18, 19, 13],
       [11, 12, 17, 12],
       [10, 17, 18, 15],
       [13, 12, 19, 19]])

In [93]:
b[0:2]

array([[15, 12, 11, 17],
       [13, 18, 19, 13]])

In [94]:
b

array([[15, 12, 11, 17],
       [13, 18, 19, 13],
       [11, 12, 17, 12],
       [10, 17, 18, 15],
       [13, 12, 19, 19]])

In [95]:
b[0:-1]

array([[15, 12, 11, 17],
       [13, 18, 19, 13],
       [11, 12, 17, 12],
       [10, 17, 18, 15]])

In [96]:
b

array([[15, 12, 11, 17],
       [13, 18, 19, 13],
       [11, 12, 17, 12],
       [10, 17, 18, 15],
       [13, 12, 19, 19]])

In [97]:
b[0,2]

11

In [98]:
np.random.randint(10,20,(4,4))

array([[14, 12, 11, 12],
       [12, 12, 18, 13],
       [10, 13, 18, 19],
       [19, 17, 17, 10]])

## Operations

In [100]:
a = np.random.randint(10,20,5)
a

array([14, 11, 14, 10, 10])

In [101]:
arr

array([0, 1, 2, 3, 4, 5])

In [102]:
arr2 = np.random.randint(0,100,(10,10))

In [103]:
arr2

array([[ 9, 65, 90, 90, 86, 75, 82, 57, 73,  1],
       [76, 78, 57, 60, 54, 73, 10, 33,  4, 76],
       [98, 90, 86, 19, 23, 28, 35, 53, 49, 25],
       [22, 54, 19,  4, 18, 56, 61, 75, 96, 42],
       [84,  8, 57, 98, 81, 81, 40, 94, 16, 55],
       [87,  2, 41, 99, 40, 63, 41, 25, 21, 26],
       [62, 57, 23, 73, 53, 91, 79, 20, 85,  9],
       [60, 80, 29, 17, 89,  1, 18,  0,  6,  9],
       [98, 22, 73, 71, 34, 51, 91, 83, 93, 32],
       [23,  9, 68,  2, 27, 75, 83, 52, 92, 80]])

In [104]:
arr

array([0, 1, 2, 3, 4, 5])

In [107]:
arr[:]

array([0, 1, 2, 3, 4, 5])

In [108]:
arr[:4]

array([0, 1, 2, 3])

In [109]:
arr2[:]

array([[ 9, 65, 90, 90, 86, 75, 82, 57, 73,  1],
       [76, 78, 57, 60, 54, 73, 10, 33,  4, 76],
       [98, 90, 86, 19, 23, 28, 35, 53, 49, 25],
       [22, 54, 19,  4, 18, 56, 61, 75, 96, 42],
       [84,  8, 57, 98, 81, 81, 40, 94, 16, 55],
       [87,  2, 41, 99, 40, 63, 41, 25, 21, 26],
       [62, 57, 23, 73, 53, 91, 79, 20, 85,  9],
       [60, 80, 29, 17, 89,  1, 18,  0,  6,  9],
       [98, 22, 73, 71, 34, 51, 91, 83, 93, 32],
       [23,  9, 68,  2, 27, 75, 83, 52, 92, 80]])

In [110]:
arr2[0:5]

array([[ 9, 65, 90, 90, 86, 75, 82, 57, 73,  1],
       [76, 78, 57, 60, 54, 73, 10, 33,  4, 76],
       [98, 90, 86, 19, 23, 28, 35, 53, 49, 25],
       [22, 54, 19,  4, 18, 56, 61, 75, 96, 42],
       [84,  8, 57, 98, 81, 81, 40, 94, 16, 55]])

In [111]:
arr2

array([[ 9, 65, 90, 90, 86, 75, 82, 57, 73,  1],
       [76, 78, 57, 60, 54, 73, 10, 33,  4, 76],
       [98, 90, 86, 19, 23, 28, 35, 53, 49, 25],
       [22, 54, 19,  4, 18, 56, 61, 75, 96, 42],
       [84,  8, 57, 98, 81, 81, 40, 94, 16, 55],
       [87,  2, 41, 99, 40, 63, 41, 25, 21, 26],
       [62, 57, 23, 73, 53, 91, 79, 20, 85,  9],
       [60, 80, 29, 17, 89,  1, 18,  0,  6,  9],
       [98, 22, 73, 71, 34, 51, 91, 83, 93, 32],
       [23,  9, 68,  2, 27, 75, 83, 52, 92, 80]])

In [114]:
arr2[1,5]

73

In [115]:
arr2

array([[ 9, 65, 90, 90, 86, 75, 82, 57, 73,  1],
       [76, 78, 57, 60, 54, 73, 10, 33,  4, 76],
       [98, 90, 86, 19, 23, 28, 35, 53, 49, 25],
       [22, 54, 19,  4, 18, 56, 61, 75, 96, 42],
       [84,  8, 57, 98, 81, 81, 40, 94, 16, 55],
       [87,  2, 41, 99, 40, 63, 41, 25, 21, 26],
       [62, 57, 23, 73, 53, 91, 79, 20, 85,  9],
       [60, 80, 29, 17, 89,  1, 18,  0,  6,  9],
       [98, 22, 73, 71, 34, 51, 91, 83, 93, 32],
       [23,  9, 68,  2, 27, 75, 83, 52, 92, 80]])

In [116]:
arr2[-5,5]

63

In [117]:
arr2[-5,-5]

63

In [ ]:
arr2

In [ ]:
arr2[-5,-5]

In [118]:
arr2

array([[ 9, 65, 90, 90, 86, 75, 82, 57, 73,  1],
       [76, 78, 57, 60, 54, 73, 10, 33,  4, 76],
       [98, 90, 86, 19, 23, 28, 35, 53, 49, 25],
       [22, 54, 19,  4, 18, 56, 61, 75, 96, 42],
       [84,  8, 57, 98, 81, 81, 40, 94, 16, 55],
       [87,  2, 41, 99, 40, 63, 41, 25, 21, 26],
       [62, 57, 23, 73, 53, 91, 79, 20, 85,  9],
       [60, 80, 29, 17, 89,  1, 18,  0,  6,  9],
       [98, 22, 73, 71, 34, 51, 91, 83, 93, 32],
       [23,  9, 68,  2, 27, 75, 83, 52, 92, 80]])

In [119]:
arr2[-1,-2]

92

In [120]:
arr2

array([[ 9, 65, 90, 90, 86, 75, 82, 57, 73,  1],
       [76, 78, 57, 60, 54, 73, 10, 33,  4, 76],
       [98, 90, 86, 19, 23, 28, 35, 53, 49, 25],
       [22, 54, 19,  4, 18, 56, 61, 75, 96, 42],
       [84,  8, 57, 98, 81, 81, 40, 94, 16, 55],
       [87,  2, 41, 99, 40, 63, 41, 25, 21, 26],
       [62, 57, 23, 73, 53, 91, 79, 20, 85,  9],
       [60, 80, 29, 17, 89,  1, 18,  0,  6,  9],
       [98, 22, 73, 71, 34, 51, 91, 83, 93, 32],
       [23,  9, 68,  2, 27, 75, 83, 52, 92, 80]])

In [121]:
arr2[::-1]

array([[23,  9, 68,  2, 27, 75, 83, 52, 92, 80],
       [98, 22, 73, 71, 34, 51, 91, 83, 93, 32],
       [60, 80, 29, 17, 89,  1, 18,  0,  6,  9],
       [62, 57, 23, 73, 53, 91, 79, 20, 85,  9],
       [87,  2, 41, 99, 40, 63, 41, 25, 21, 26],
       [84,  8, 57, 98, 81, 81, 40, 94, 16, 55],
       [22, 54, 19,  4, 18, 56, 61, 75, 96, 42],
       [98, 90, 86, 19, 23, 28, 35, 53, 49, 25],
       [76, 78, 57, 60, 54, 73, 10, 33,  4, 76],
       [ 9, 65, 90, 90, 86, 75, 82, 57, 73,  1]])

In [122]:
arr2

array([[ 9, 65, 90, 90, 86, 75, 82, 57, 73,  1],
       [76, 78, 57, 60, 54, 73, 10, 33,  4, 76],
       [98, 90, 86, 19, 23, 28, 35, 53, 49, 25],
       [22, 54, 19,  4, 18, 56, 61, 75, 96, 42],
       [84,  8, 57, 98, 81, 81, 40, 94, 16, 55],
       [87,  2, 41, 99, 40, 63, 41, 25, 21, 26],
       [62, 57, 23, 73, 53, 91, 79, 20, 85,  9],
       [60, 80, 29, 17, 89,  1, 18,  0,  6,  9],
       [98, 22, 73, 71, 34, 51, 91, 83, 93, 32],
       [23,  9, 68,  2, 27, 75, 83, 52, 92, 80]])

In [123]:
arr2[::-2]

array([[23,  9, 68,  2, 27, 75, 83, 52, 92, 80],
       [60, 80, 29, 17, 89,  1, 18,  0,  6,  9],
       [87,  2, 41, 99, 40, 63, 41, 25, 21, 26],
       [22, 54, 19,  4, 18, 56, 61, 75, 96, 42],
       [76, 78, 57, 60, 54, 73, 10, 33,  4, 76]])

In [124]:
arr2

array([[ 9, 65, 90, 90, 86, 75, 82, 57, 73,  1],
       [76, 78, 57, 60, 54, 73, 10, 33,  4, 76],
       [98, 90, 86, 19, 23, 28, 35, 53, 49, 25],
       [22, 54, 19,  4, 18, 56, 61, 75, 96, 42],
       [84,  8, 57, 98, 81, 81, 40, 94, 16, 55],
       [87,  2, 41, 99, 40, 63, 41, 25, 21, 26],
       [62, 57, 23, 73, 53, 91, 79, 20, 85,  9],
       [60, 80, 29, 17, 89,  1, 18,  0,  6,  9],
       [98, 22, 73, 71, 34, 51, 91, 83, 93, 32],
       [23,  9, 68,  2, 27, 75, 83, 52, 92, 80]])

In [125]:
arr2[::-3]

array([[23,  9, 68,  2, 27, 75, 83, 52, 92, 80],
       [62, 57, 23, 73, 53, 91, 79, 20, 85,  9],
       [22, 54, 19,  4, 18, 56, 61, 75, 96, 42],
       [ 9, 65, 90, 90, 86, 75, 82, 57, 73,  1]])

In [126]:
arr

array([0, 1, 2, 3, 4, 5])

In [127]:
arr.max() 

5

In [128]:
arr.min()

0

In [129]:
arr

array([0, 1, 2, 3, 4, 5])

In [130]:
arr.mean()

2.5

In [131]:
arr.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [132]:
>>> from numpy import *
>>> a = array([1,2,3,4,9])
>>> median(a)

3.0

In [133]:
arr

array([0, 1, 2, 3, 4, 5])

In [134]:
arr.reshape(2,3)  

array([[0, 1, 2],
       [3, 4, 5]])

In [135]:
arr.reshape(6,1)  

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [136]:
arr.reshape(1,6) 

array([[0, 1, 2, 3, 4, 5]])

In [137]:
arr.reshape(1,6) 

array([[0, 1, 2, 3, 4, 5]])

In [138]:
arr

array([0, 1, 2, 3, 4, 5])

In [140]:
arr.reshape(1,5) 

ValueError: cannot reshape array of size 6 into shape (1,5)

In [141]:
arr.reshape(3,2,order='C') 

array([[0, 1],
       [2, 3],
       [4, 5]])

In [142]:
arr.reshape(3,2,order='F') 

array([[0, 3],
       [1, 4],
       [2, 5]])

In [143]:
arr.reshape(3,2,order='A') 

array([[0, 1],
       [2, 3],
       [4, 5]])

In [144]:
arr.reshape(3,2,order='K') 

ValueError: order 'K' is not permitted for reshaping

In [145]:
arr

array([0, 1, 2, 3, 4, 5])

In [146]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [147]:
arr.reshape(1,4)  

ValueError: cannot reshape array of size 6 into shape (1,4)

In [8]:
arr.reshape(1,6)  

NameError: name 'arr' is not defined

In [ ]:
arr.reshape(6,1)  

In [5]:
arr.reshape(2,6) 

NameError: name 'arr' is not defined

In [1]:
arr.reshape(3,3) 

NameError: name 'arr' is not defined

In [ ]:
arr

In [ ]:
arr.reshape(3,2)  

## Indexing

In [148]:
mat = np.arange(0,100).reshape(10,10) 

In [149]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [150]:
row = 4
col = 5

In [151]:
col

5

In [152]:
row

4

In [153]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [154]:
mat[row,col] 

45

In [155]:
mat[4,5] 

45

In [156]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [157]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [158]:
col = 6

In [159]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [160]:
# With Slices
mat[:,col] 

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [161]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [162]:
mat[row,:]

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [163]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [167]:
mat[:,col]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [166]:
mat[:col] 

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [168]:
row

4

In [169]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [174]:
mat[:row]  

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [172]:
mat[row:] 

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [175]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [176]:
mat[:,8] 

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [177]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [178]:
mat[:,-1] 

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [179]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [180]:
row

4

In [181]:
col

6

In [ ]:
mat[:,col] 

In [ ]:
mat

In [ ]:
mat[1,4]

In [ ]:
mat

In [ ]:
mat[1:4]

In [182]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [183]:
mat[3:-3]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [184]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [185]:
mat[0]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [186]:
mat[6]

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [188]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [189]:
mat[6:]

array([[60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [190]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [191]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [192]:
mat[5:7]

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [193]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [194]:
mat[0:10]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [195]:
mat[0:10:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:
mat[0:10]

In [ ]:
mat[0:10:3]

In [ ]:
mat

In [ ]:
mat[4:]

In [ ]:
mat

In [ ]:
mat[:4]

In [ ]:
mat

In [ ]:
mat[::-1]

In [ ]:
mat[::-2]

In [ ]:
mat

In [ ]:
mat[::-3]

In [ ]:
mat

In [ ]:
mat[::-5]

In [196]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [197]:
mat[2:6]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [198]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [199]:
mat[2:6,2:4] # 1:5 --> only row part /// 1:3 -- it indicates only column parts

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [ ]:
mat

In [ ]:
mat[0,1]

In [ ]:
mat[1,6]

In [ ]:
mat

In [ ]:
mat[1:6]

In [ ]:
mat[1:]

In [ ]:
mat

In [ ]:
mat[:6]

In [ ]:
mat[0:1]

In [ ]:
mat

In [ ]:
mat[3:5]

In [ ]:
mat[3,5]

In [200]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [201]:
mat[1:2,2:4]

array([[12, 13]])

In [ ]:
mat

In [ ]:
mat[2:3,2:3]

In [ ]:
mat

In [ ]:
mat[3:5,2:4,]

In [202]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [203]:
mat[2:3,4:5]

array([[24]])

## Masking

In [204]:
mat # we also called as filter

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [205]:
id(mat)

2459509638704

In [206]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [207]:
mat < 50

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [208]:
mat > 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [209]:
mat == 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [210]:
mat[mat==50] 

array([50])

In [211]:
a1 = mat[mat<50] 
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [212]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [213]:
a2 = mat[mat>50] 
a2

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [214]:
a3 = mat[mat>=50] 
a3

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [216]:
a4 = mat[mat==50]
a4

array([50])

In [217]:
mat>50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [218]:
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [219]:
a2

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])